// src/core/calendar-service.ts
import { calendar_v3 } from 'googleapis';
import logger from '../logger';
import { YouTubeScript } from './youtube-script-generator';

type Calendar = calendar_v3.Calendar;

export interface CalendarEvent {
  id: string;
  summary: string;
  description?: string | null;
  start?: {
    dateTime?: string | null;
    date?: string | null;
  };
  end?: {
    dateTime?: string | null;
    date?: string | null;
  };
  htmlLink?: string | null;
}

/**
 * Fetches calendar events from the next N days
 */
export async function fetchUpcomingEvents(
  calendar: Calendar,
  daysAhead: number = 10
): Promise<CalendarEvent[]> {
  logger.info(`Fetching calendar events for the next ${daysAhead} days...`);

  const now = new Date();
  const futureDate = new Date();
  futureDate.setDate(now.getDate() + daysAhead);

  try {
    const response = await calendar.events.list({
      calendarId: 'primary',
      timeMin: now.toISOString(),
      timeMax: futureDate.toISOString(),
      singleEvents: true,
      orderBy: 'startTime',
    });

    const events = response.data.items || [];
    logger.info(`Found ${events.length} events in the next ${daysAhead} days`);

    return events.map((event) => ({
      id: event.id!,
      summary: event.summary || 'Untitled Event',
      description: event.description,
      start: event.start,
      end: event.end,
      htmlLink: event.htmlLink,
    }));
  } catch (error) {
    logger.error({ error }, 'Failed to fetch calendar events');
    throw error;
  }
}

/**
 * Updates a calendar event's description
 */
export async function updateEventDescription(
  calendar: Calendar,
  eventId: string,
  newDescription: string
): Promise<void> {
  logger.info({ eventId }, 'Updating calendar event description...');

  try {
    // First, get the current event
    const currentEvent = await calendar.events.get({
      calendarId: 'primary',
      eventId: eventId,
    });

    // Update with new description
    await calendar.events.patch({
      calendarId: 'primary',
      eventId: eventId,
      requestBody: {
        description: newDescription,
      },
    });

    logger.info({ eventId }, 'Successfully updated calendar event');
  } catch (error) {
    logger.error({ error, eventId }, 'Failed to update calendar event');
    throw error;
  }
}

/**
 * Creates a new calendar event
 */
export async function createCalendarEvent(
  calendar: Calendar,
  event: {
    summary: string;
    description?: string;
    startDateTime: string; // ISO 8601 format
    endDateTime: string; // ISO 8601 format
    timeZone?: string;
  }
): Promise<CalendarEvent> {
  logger.info({ summary: event.summary }, 'Creating calendar event...');

  try {
    const response = await calendar.events.insert({
      calendarId: 'primary',
      requestBody: {
        summary: event.summary,
        description: event.description,
        start: {
          dateTime: event.startDateTime,
          timeZone: event.timeZone || 'America/Los_Angeles',
        },
        end: {
          dateTime: event.endDateTime,
          timeZone: event.timeZone || 'America/Los_Angeles',
        },
      },
    });

    const createdEvent = response.data;
    logger.info(
      { eventId: createdEvent.id, htmlLink: createdEvent.htmlLink },
      'Successfully created calendar event'
    );

    return {
      id: createdEvent.id!,
      summary: createdEvent.summary || 'Untitled Event',
      description: createdEvent.description,
      start: createdEvent.start,
      end: createdEvent.end,
      htmlLink: createdEvent.htmlLink,
    };
  } catch (error) {
    logger.error({ error, summary: event.summary }, 'Failed to create calendar event');
    throw error;
  }
}

/**
 * Formats a script into a calendar-friendly description
 */
export function formatScriptForCalendar(
  originalDescription: string | undefined,
  script: YouTubeScript
): string {
  const divider = '\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n';
  const originalSection = originalDescription
    ? `ORIGINAL EVENT NOTES:\n${originalDescription}${divider}`
    : '';

  const scriptTableFormatted = script.scriptTable
    .map((row, i) => `${i + 1}. ${row.sentence}\n   📹 B-Roll: ${row.bRoll}`)
    .join('\n\n');

  return `${originalSection}📹 YOUTUBE SHORTS SCRIPT - Generated by AI

🎬 TITLE: ${script.title}

🎯 MAIN CONCEPT: ${script.mainConcept}

🪝 HOOK (0-2s):
${script.hook}

📝 SCRIPT & B-ROLL:
${scriptTableFormatted}

📢 CALL TO ACTION:
${script.cta}

🏷️ HASHTAGS: ${script.hashtags.join(' ')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated on: ${new Date().toISOString()}`;
}
